version: "3.8"

x-common-environment: &common_env
  GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
  GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
  GF_SERVER_ROOT_URL: http://${DOMAIN}:3000
  GF_SERVER_DOMAIN: ${DOMAIN}
  GF_USERS_ALLOW_SIGN_UP: "false"
  GF_AUTH_ANONYMOUS_ENABLED: "false"
  GF_ANALYTICS_REPORTING_ENABLED: "false"

services:

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - grafana-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  # New Service Added: SNMP Exporter
  snmp-exporter:
    build:
      context: ../
    image: my-snmp-exporter:fixed
    restart: unless-stopped
    network_mode: "host"
    #ports:
    #  - "9116:9116" # Exporter default port
    #volumes:
    #  # We are mapping the SNMP configuration file from outside the Compose folder.
    #  - /opt/grafana/snmp.yml:/etc/snmp_exporter/snmp.yml:ro

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - postgres
      - prometheus
    restart: unless-stopped
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: ${POSTGRES_HOST}:5432
      GF_DATABASE_NAME: ${POSTGRES_DB}
      GF_DATABASE_USER: ${POSTGRES_USER}
      GF_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      #GF_INSTALL_PLUGINS: "alexanderzobnin-zabbix-app 4.6.0"

      <<: *common_env

    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ../provisioning:/etc/grafana/provisioning:ro
      - ../dashboards:/var/lib/grafana/dashboards-json:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --timeout=5 http://127.0.0.1:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.53.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

volumes:
  grafana-data:
  grafana-postgres-data:
  prometheus-data:
  loki-data:
